module.exports = {
  ru: {
    "Skip navigation": "Пропустить навигацию",
    "Drafts": "Черновики",
    "Andrey Gurylev": "Андрей Гурылев",
    "Andrey Gurylev's website": "Сайт Андрея Гурылева",
    "about site": "о сайте",
    "Edit this page": "Редактировать эту страницу",
    "published": "опубликовал",
    "the article": "статью",
    "in the category": "в категории",
    "and tagged it with": "и пометил тегами",
    "Can be read in": "Можно прочитать за",
    "Contents": "Оглавление",
    "↑ To the top of the article": "↑ К началу статьи",
    "Skip the contents": "Пропустить оглавление",
    "← Back to section": "← Вернуться в раздел",
    "Next post:": "Следующий пост:",
    "Previous post:": "Предыдущий пост:",
    "Draft, not available yet": "Черновик, пока недоступен",
    "Search the current site": "Искать на сайте",
    "Search": "Найти",
    "There's nothing here": "Здесь ничего нет"
  },
}
